name: Get Versions

on:
  schedule:
    - cron: '0 6 * * *' # Tous les jours à 06h00 UTC
  workflow_dispatch: # Permet aussi une exécution manuelle

jobs:
  fetch-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Debug git status
        run: |
          git status
          git remote -v

      # Exécute le script Python pour récupérer les versions
      - name: Fetch versions
        run: |
          python src/fetch_versions.py

      - name: Commit version file
        run: |
          set -e
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add data/*.version || echo "No .version files to add"
          git diff --cached --quiet || git commit -m "Update versions"
          git push
